//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangSave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public int ID { get; set; }
        public int MaMonDo { get; set; }
        public string IDNguoiDang { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime ThoiGian { get; set; }
    
        public virtual ThongTinMonDo ThongTinMonDo { get; set; }
        public virtual ThongTinNguoiDung ThongTinNguoiDung { get; set; }
    }
}
