//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangSave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyTraoDoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DangKyTraoDoi()
        {
            this.LichSuTraoDois = new HashSet<LichSuTraoDoi>();
        }
    
        public int ID { get; set; }
        public int IDMonDoDang { get; set; }
        public int IDMonDoNhan { get; set; }
        public int IDNguoiDang { get; set; }
        public int IDNguoiNhan { get; set; }
        public System.DateTime NgayDangKy { get; set; }
        public string SDTNguoiNhan { get; set; }
        public string DiaChiNhanHang { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuTraoDoi> LichSuTraoDois { get; set; }
    }
}
