//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangSave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuTraoDoi
    {
        public int ID { get; set; }
        public int IDMonDoDang { get; set; }
        public int IDMonDoTraoDoi { get; set; }
        public int IDTraoDoi { get; set; }
        public System.DateTime NgayTraoDoi { get; set; }
        public string HinhThucTraoDoi { get; set; }
    
        public virtual DangKyTraoDoi DangKyTraoDoi { get; set; }
        public virtual ThongTinMonDo ThongTinMonDo { get; set; }
        public virtual ThongTinMonDo ThongTinMonDo1 { get; set; }
    }
}
