//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangSave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinMonDo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTinMonDo()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.LichSuTraoDois = new HashSet<LichSuTraoDoi>();
            this.LichSuTraoDois1 = new HashSet<LichSuTraoDoi>();
            this.ThuocTinhs = new HashSet<ThuocTinh>();
        }
    
        public int MaMonDo { get; set; }
        public int MaDanhMuc { get; set; }
        public string NguoiDang { get; set; }
        public System.DateTime NgayDang { get; set; }
        public int MaHienThi { get; set; }
        public string HinhAnh { get; set; }
        public string TenMonDo { get; set; }
        public string TinhTrang { get; set; }
        public string HinhThucTraoDoi { get; set; }
        public string TrangThai { get; set; }
        public int SoLuong { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuTraoDoi> LichSuTraoDois { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuTraoDoi> LichSuTraoDois1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThuocTinh> ThuocTinhs { get; set; }
    }
}
