//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangSave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int ID { get; set; }
        public string MaNguoiDung { get; set; }
        public string NoiDungThongBao { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public string TrangThai { get; set; }
    
        public virtual ThongTinNguoiDung ThongTinNguoiDung { get; set; }
    }
}
