//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VanLangSave.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuocTinh
    {
        public int MaThuocTinh { get; set; }
        public int MaSanPham { get; set; }
        public string TenThuocTinh { get; set; }
    
        public virtual ChiTietThuocTinh ChiTietThuocTinh { get; set; }
        public virtual ThongTinMonDo ThongTinMonDo { get; set; }
    }
}
